import { Geist, Geist_Mono, Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={`font-sans ${inter.variable}`} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Script id="remove-browser-extension-attributes" strategy="beforeInteractive">
          {`
            (function () {
              var patterns = [/^bis_/, /^__processed_/];

              function cleanNode(node) {
                if (!node || !node.attributes) return;

                Array.prototype.slice.call(node.attributes).forEach(function (attribute) {
                  if (patterns.some(function (pattern) { return pattern.test(attribute.name); })) {
                    node.removeAttribute(attribute.name);
                  }
                });
              }

              function cleanTree(root) {
                cleanNode(root);
                Array.prototype.forEach.call(root.querySelectorAll("*"), cleanNode);
              }

              cleanTree(document.documentElement);

              new MutationObserver(function (mutations) {
                mutations.forEach(function (mutation) {
                  if (mutation.type === "attributes") {
                    cleanNode(mutation.target);
                  }

                  mutation.addedNodes.forEach(function (node) {
                    if (node.nodeType === Node.ELEMENT_NODE) {
                      cleanTree(node);
                    }
                  });
                });
              }).observe(document.documentElement, {
                attributes: true,
                childList: true,
                subtree: true
              });
            })();
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}
