import "../globals.css";
import TopbarMenu from "@/components/topbar-menu";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange={false}
    >
      <TooltipProvider>
        <div className="w-6xl max-w-full m-auto">
          <TopbarMenu />
          {children}
        </div>
      </TooltipProvider>
    </ThemeProvider>
  );
}
